GET http://127.0.0.1:8085/userTest?page=1&limit=10

###
GET http://127.0.0.1:8085/userTest/list?page=1&limit=10

###
GET http://127.0.0.1:8085/userTest/1

###
GET http://127.0.0.1:8085/userTest/count

###

GET http://127.0.0.1:8085/userTest/storeRedis

###